fixed the compilation issue of opengl_3d on Ubuntu 16.04 had to add the X11 library explicitly, the error was: usr/bin/ld: /home/omidm/cloud/src/nimbus/applications/physbam/physbam-lib/Public_Library/Build/Release/libPhysBAM_Rendering-OpenGL.a(OPENGL_GLX_PBUFFER.cpp.o): undefined reference to symbol 'XSetErrorHandler' //usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line